extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  azuremonitor:
    instrumentation_key: ${env:AZUREMONITOR_INSTRUMENTATION_KEY}

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
  extensions: [health_check]
