name: chorus images

on:
  push:
    paths:
      - ".github/workflows/chorusimage.yml"
    branches:
      - main

env:
  REGISTRY: ghcr.io
  ORG: chorus-ai

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./etl
            image: ghcr.io/chorus-ai/chorus-etl
          - dockerfile: ./lab
            image: ghcr.io/chorus-ai/chorus-lab
          - dockerfile: ./otel
            image: ghcr.io/chorus-ai/chorus-otel
          - dockerfile: ./prefect
            image: ghcr.io/chorus-ai/chorus-prefect
          - dockerfile: ./www-admin
            image: ghcr.io/chorus-ai/chorus-www-admin
          - dockerfile: ./www-dgs
            image: ghcr.io/chorus-ai/chorus-www-dgs

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to a container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
          platforms: |
            linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

