name: chorus images rcim

on:
  push:
    branches:
      - main
    paths:
      - 'www-rcim/**'
      - 'firefox-rcim/**'
      - '.github/workflows/chorus-rcim.yml'

env:
  REGISTRY: ghcr.io
  ORG: chorus-ai

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./www-rcim/Dockerfile
            image: ghcr.io/chorus-ai/chorus-www-rcim
            context: ./www-rcim
          - dockerfile: ./firefox-rcim/Dockerfile
            image: ghcr.io/chorus-ai/chorus-firefox-rcim
            context: ./firefox-rcim
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to a container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: b2ai-googleform-bot
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
          platforms: |
            linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
