name: chorus images portals

on:
  push:
    branches:
      - main
    paths:
      - 'lab/**'
      - 'otel/**'
      - 'prefect/**'
      - 'webapi/**'
      - 'www-admin/**'
      - 'www-dgs/**'
      - 'www-challenge/**'

env:
  REGISTRY: ghcr.io
  ORG: chorus-ai

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./lab/Dockerfile
            image: ghcr.io/chorus-ai/chorus-lab
            context: ./lab
          - dockerfile: ./otel/Dockerfile
            image: ghcr.io/chorus-ai/chorus-otel
            context: ./otel
          - dockerfile: ./prefect/Dockerfile
            image: ghcr.io/chorus-ai/chorus-prefect
            context: ./prefect
          - dockerfile: ./webapi/Dockerfile
            image: ghcr.io/chorus-ai/chorus-webapi
            context: ./webapi
          - dockerfile: ./www-admin/Dockerfile
            image: ghcr.io/chorus-ai/chorus-www-admin
            context: ./www-admin
          - dockerfile: ./www-challenge/Dockerfile
            image: ghcr.io/chorus-ai/chorus-www-challenge
            context: ./www-challenge
          - dockerfile: ./www-dgs/Dockerfile
            image: ghcr.io/chorus-ai/chorus-www-dgs
            context: ./www-dgs
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to a container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: b2ai-googleform-bot
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
          platforms: |
            linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

